### PR TITLE
Add NotoMono-Regular v1.00 (nee DroidSansMono).

### PR DESCRIPTION
**Pull request by dougfelt**
This changes licensing of the former Droid-branded font to match Noto
licensing (OFL, installable).

The name and OS/2 table has been updated to reflect Monotype/Google
ownership. Additional changes for lint purposes are:
 - PlatformID 1 name data was dropped, platformID 3 was retained.
 - Win/Typo line metrics (but not glyph bounds) were adjusted to match
   the hhea values.
 - PlatformID 0 cmap was dropped, platformID 3 was retained.
 - Empty glyphs for null and CR have been added to the cmap (null
   has zero advance).

Users should note that NotoMono has a much smaller repertoire than
NotoSans/Serif; they are not in the same family.

### CODE REVIEW

**Comment by dougfelt** [comment]
I'll just go ahead and accept the pull request.

**Comment by rastus-vernon** [comment]
@dougfelt
Can this font be released on https://google.com/get/noto (if that wouldn't conflict with the roadmap/phases, I don't understand how those work)? Then it can be packaged for Linux distributions that have the Noto family (see [redhat#1321685](https://bugzilla.redhat.com/show_bug.cgi?id=1321685)).

**Comment by pravins** [comment]
@roozbehp To make this improvement in Fedora 24, will be very nice, if we can have minor release with this addition. :)

**Comment by pravins** [comment]
Ping...

**Pull request merged**
