### PR TITLE
Simplify structure of Noto site

### PR DESCRIPTION
**Pull request by brawer**
See here for rendered HTML:
* https://github.com/brawer/noto-fonts/blob/readme-cleanup/README.md
* https://github.com/brawer/noto-fonts/blob/readme-cleanup/FAQ.md

https://github.com/googlei18n/noto-fonts/issues/640

### CODE REVIEW

**Comment by davelab6** [comment]
For the FAQ, by moving the structural headline markup to bold formatting markup, you lose the ability to link to specific sections, as Github will generate named anchors for each headline, eg

https://github.com/googlei18n/noto-fonts/blob/master/FAQ.md#how-do-i-file-a-bug

**Comment by brawer** [comment]
Thanks for pointing this out! Changed.

**Comment by xiangyexiao** [comment]
GitHub FAQ seems to have a big overlap with FAQ at http://www.google.com/get/noto/help/faq/.  It probably doesn't matter a lot since we don't update it frequently, but want to point this out if you have any suggestions. GitHub FAQ is quicker to update than ~/get/noto.

**Comment by davelab6** [comment]
Perhaps ideally they would be unified, and
https://github.com/googlei18n/nototools updated to use this markdown file
on that website? :)

**Comment by dougfelt** [comment]
nototools does not control the FAQ and other text files used on that website.

**Comment by davelab6** [comment]
Oh! I misunderstood that, sorry :) Which site does those tools control?

**Comment by dougfelt** [comment]
The tools generate the font files and the metadata describing the fonts.
It doesn't control the text pages and the code controlling the UI, which
are built by the designer.  The idea was for some of these text pages to
fetch from the github repo but it appears some of them still don't.

**Comment by dougfelt** [comment]
Sorry Sascha, I thought Xiangye had LGTM'd this.

**Pull request merged**
