### PR TITLE
Remove old UI versions of NotoSans.

### PR DESCRIPTION
**Pull request by dougfelt**

### CODE REVIEW

**Comment by dougfelt** [comment]
Note, Jungshik said these existed to work around fontconfig issues with fallback when we wanted UI fonts.  We needed an LGC font to head this fallback chain-- but these fonts were exactly the same as the non-ui fonts except for the name.  In a .ttc this didn't matter, all the tables but the name table were shared.

He says fontconfig should now provide other/better ways to handle this, so he agrees we can remove these.

@jungshik, did I get that right?

**Comment by madig** [comment]
Just to be clear -- "Noto Sans" is the same as "Noto Sans UI"? We're trying to use Noto as the default fallback in Fedora with UI fonts for UIs and are a bit confused: https://pagure.io/fedora-workstation/issue/36.

**Comment by marekjez86** [comment]
@madig : Noto Sans has UI font metrics. If you want non-UI version please use Noto Sans Display.

**Comment by madig** [comment]
I'm confused.

Does "Display" imply it's to be used for larger text sizes? Is "Display" to be used for regular documents? For UI use, should one pair "Noto Sans" with UI fonts if they exist and with "normal"/non-"Display" variants if not?

**Comment by twardoch** [comment]
Yes, Display is for larger sizes. 

Noto Sans UI is the same as NotoSans except the font metrics i.e. linespacing values. The UI versions are a bit tighter and, I think, harmonized across different scripts. For general use, the non-UI versions are better.

**Pull request merged**
