### PR TITLE
Promote some phase 3 alpha fonts to release status.

### PR DESCRIPTION
**Pull request by dougfelt**
Initial phase 3 versions of Armenian, Cherokee, and Hebrew.

These are modified versions of the files under alpha/from-pipeline.
These include some modifications to fix minor lint issues and to put
additional information into the version string, using the quik-n-dirty
autofix_for_phase3 tool in nototools.

Hinted versions were autohinted by ttfautohint.  These contain TTFA
tables that encode the flags it used.

Version numbers for phase 3 have major version of two and a 3-digit
minor version.  Armenian was already at version 2 so got a higher
minor version so as to reduce confusion.

A change summary follows:

added
  hinted/NotoSansCherokee-Regular.ttf
  hinted/NotoSerifHebrew-Bold.ttf
  hinted/NotoSerifHebrew-Regular.ttf
  unhinted/NotoSerifHebrew-Bold.ttf
  unhinted/NotoSerifHebrew-Regular.ttf

changed
  hinted/NotoSansArmenian-Bold.ttf
    version: 2.03 vs 2.040
    size: 25964 vs 28936 (2972 bytes bigger)
    tables: changed fpgm(+1453), glyf(+1152), prep(-133), cvt (-118), name(+106); added TTFA(484); removed GDEF
    glyphs: 98 vs 103 (5 more glyphs)
    chars: 97 vs 100 (3 more chars)
    cmap removed: FEFF
    cmap added: 002D, 058D..058E, 2010
  hinted/NotoSansArmenian-Regular.ttf
    version: 2.03 vs 2.040
    size: 25292 vs 28812 (3520 bytes bigger)
    tables: changed fpgm(+1453), glyf(+1238), GPOS(+298), name(+174), cvt (-120); added TTFA(484); removed GDEF
    glyphs: 98 vs 103 (5 more glyphs)
    chars: 97 vs 100 (3 more chars)
    cmap removed: FEFF
    cmap added: 002D, 058D..058E, 2010
  hinted/NotoSansHebrew-Bold.ttf
    version: 1.04 vs 2.000
    size: 27216 vs 26152 (1064 bytes smaller)
    tables: changed GPOS(-4332), glyf(+1816), fpgm(+1465), GSUB(-676), cvt (-578); added TTFA(484)
    glyphs: 155 vs 149 (6 fewer glyphs)
    chars: 144 vs 145 (1 more char)
    cmap removed: FEFF
    cmap added: 002D, 2010
  hinted/NotoSansHebrew-Regular.ttf
    version: 1.04 vs 2.000
    size: 26912 vs 26008 (904 bytes smaller)
    tables: changed GPOS(-4196), glyf(+1760), fpgm(+1465), GSUB(-676), cvt (-578); added TTFA(484)
    glyphs: 155 vs 149 (6 fewer glyphs)
    chars: 144 vs 145 (1 more char)
    cmap removed: FEFF
    cmap added: 002D, 2010
  hinted/NotoSerifArmenian-Bold.ttf
    version: 2.03 vs 2.040
    size: 27216 vs 28268 (1052 bytes bigger)
    tables: changed fpgm(+1453), GPOS(-1066), glyf(+228), cvt (-126), name(+106); added TTFA(484); removed GDEF
    glyphs: 98 vs 103 (5 more glyphs)
    chars: 97 vs 100 (3 more chars)
    cmap removed: FEFF
    cmap added: 002D, 058D..058E, 2010
  hinted/NotoSerifArmenian-Regular.ttf
    version: 2.03 vs 2.040
    size: 26592 vs 28824 (2232 bytes bigger)
    tables: changed fpgm(+1453), GPOS(+440), glyf(-182), name(+176), cvt (-124); added TTFA(484); removed GDEF
    glyphs: 98 vs 103 (5 more glyphs)
    chars: 97 vs 100 (3 more chars)
    cmap removed: FEFF
    cmap added: 002D, 058D..058E, 2010
  unhinted/NotoSansArmenian-Bold.ttf
    version: 2.03 vs 2.040
    size: 17232 vs 16892 (340 bytes smaller)
    tables: changed glyf(-380), post(+55), GPOS(-44), name(+42), cmap(+22); removed GDEF, gasp
    glyphs: 98 vs 103 (5 more glyphs)
    chars: 97 vs 100 (3 more chars)
    cmap removed: FEFF
    cmap added: 002D, 058D..058E, 2010
  unhinted/NotoSansArmenian-Regular.ttf
    version: 2.03 vs 2.040
    size: 16720 vs 16976 (256 bytes bigger)
    tables: changed GPOS(+298), glyf(-160), name(+74), post(+55), cmap(+22); removed GDEF, gasp
    glyphs: 98 vs 103 (5 more glyphs)
    chars: 97 vs 100 (3 more chars)
    cmap removed: FEFF
    cmap added: 002D, 058D..058E, 2010
  unhinted/NotoSansCherokee-Regular.ttf
    version: 1.03 vs 2.000
    size: 35428 vs 61348 (25920 bytes bigger)
    tables: changed glyf(+17388), GPOS(+4742), post(+2306), hmtx(+718), GSUB(+390); removed gasp
    glyphs: 89 vs 273 (184 more glyphs)
    chars: 90 vs 186 (96 more chars)
    cmap removed: FEFF
    cmap added: 0300..0302, 0304, 030B..030C, 0323..0324, 0330..0331, 13F5, 13F8..13FD, AB70..ABBF
  unhinted/NotoSansHebrew-Bold.ttf
    version: 1.04 vs 2.000
    size: 20704 vs 15804 (4900 bytes smaller)
    tables: changed GPOS(-4332), GSUB(-676), glyf(-540), post(+475), cmap(+112); removed gasp
    glyphs: 155 vs 149 (6 fewer glyphs)
    chars: 144 vs 145 (1 more char)
    cmap removed: FEFF
    cmap added: 002D, 2010
  unhinted/NotoSansHebrew-Regular.ttf
    version: 1.04 vs 2.000
    size: 20516 vs 15908 (4608 bytes smaller)
    tables: changed GPOS(-4196), GSUB(-676), post(+475), glyf(-424), cmap(+112); removed gasp
    glyphs: 155 vs 149 (6 fewer glyphs)
    chars: 144 vs 145 (1 more char)
    cmap removed: FEFF
    cmap added: 002D, 2010
  unhinted/NotoSerifArmenian-Bold.ttf
    version: 2.03 vs 2.040
    size: 17492 vs 15712 (1780 bytes smaller)
    tables: changed GPOS(-1066), glyf(-802), post(+55), name(+42), cmap(+22); removed GDEF, gasp
    glyphs: 98 vs 103 (5 more glyphs)
    chars: 97 vs 100 (3 more chars)
    cmap removed: FEFF
    cmap added: 002D, 058D..058E, 2010
  unhinted/NotoSerifArmenian-Regular.ttf
    version: 2.03 vs 2.040
    size: 16892 vs 16568 (324 bytes smaller)
    tables: changed glyf(-876), GPOS(+440), name(+74), post(+55), cmap(+22); removed GDEF, gasp
    glyphs: 98 vs 103 (5 more glyphs)
    chars: 97 vs 100 (3 more chars)
    cmap removed: FEFF
    cmap added: 002D, 058D..058E, 2010

### CODE REVIEW

**Comment by jungshik** [comment]
A question about GDEF removal in Armenian? Is it expected? 

It's interesting that the Hebrew font glyph count gets smaller. 

How big is a TTFA table? I guess it's tiny so that we don't have to worry about its size.

**Comment by jungshik** [comment]
Oh. TTFA is 484 bytes. Sorry for missing it.

**Comment by dougfelt** [comment]
Yes, I was thinking we can always strip TTFA if we need to.  Android only uses unhinted fonts so it wouldn't be impacted.  I thought CrOS also only used unhinted fonts?

**Comment by dougfelt** [comment]
I'm assuming dropping the GDEF from the Armenian is ok.  I'm not looking at these fonts myself, instead I'm taking Marek's and Kat's word that they render ok.

**Comment by jungshik** [comment]
Currently, Chrome OS uses hinted fonts (manually). I haven't yet decided what to do about phase 3 fonts. 

IIRC, Armenian has a couple of character sequences that need GSUB/GPOS (my memory might be faulty). Even if it does, I'm not sure if we need GDEF.

**Comment by brawer** [comment]
According to the ttfautohint docs, the TTFA table is purely informational. Not even FreeType uses it.

**Comment by dougfelt** [comment]
That's the idea.  It's handy to have it in the binary so later we can refer to it to see what we asked ttfautohint to do, but it doesn't get in the way of other processes.  We can remove it for size reasons if we want, but it's small.  I intentionally put it in there, ttfautohint only annotates the version string in the name table by default.

**Pull request merged**
