### PR TITLE
Update Khmer post table names, and other fixes.

### PR DESCRIPTION
**Pull request by dougfelt**
This completes fix noto-fonts#564.  The previous updates neglected
to fix the post tables in the hinted fonts, and then neglected to fix them
in the serif fonts.  These changes should have fixed all the Khmer fonts.

In addition this fixes some other problems that lint found, in particular
it makes some changes to the typographic ascent/descent/linegap.

### CODE REVIEW

**Comment by dougfelt** [comment]
@jungshik, please take a look

**Comment by dougfelt** [comment]
Sigh, I really should know better.  The Serif versions also have bad post tables.  This change is ok but this still does not fix #564

**Comment by dougfelt** [comment]
@jungshik?

**Comment by jungshik** [comment]
Sans-serif fonts all look good (I compared all the changed tables). 
Serif: I'll take a look in an hour or so :-). BTW, why did prep and fpgm change in Serif? Perhaps, they're cleaned up?

**Comment by dougfelt** [comment]
@jungshik re prep and fpgm, I don't know.  I generated ttx from the fonts I had, updated the post (and name, etc. tables), then regenerated the fonts.  I'm assuming the rename of the glyphs via updating the post wouldn't impact prep and fpgm.  Maybe these fonts hadn't been run through ttx before and it optimized prep and fpgm when it regenerated them.

**Comment by dougfelt** [comment]
jungshik says this is probably ok, so...

**Pull request merged**
