### PR TITLE
Update Khmer post tables, and add cmap entries for null and return.

### PR DESCRIPTION
**Pull request by dougfelt**
Updates to v1.03. Fixes google18n/noto-fonts#564.

The missing cmap entries were failing lint checks.  The glyph data were
already in the font, they just weren't referenced in the cmap.

changed
  unhinted/NotoSansKhmer-Bold.ttf
    version: 1.02 vs 1.03 
    size: 35760 vs 36144 (384 bytes bigger)
    tables: changed post(+368), cmap(+16), 2 others
    chars: 190 vs 192 (2 more chars)
    cmap added: 0000, 000D
  unhinted/NotoSansKhmer-Regular.ttf
    version: 1.02 vs 1.03 
    size: 36760 vs 37144 (384 bytes bigger)
    tables: changed post(+368), cmap(+16), 2 others
    chars: 190 vs 192 (2 more chars)
    cmap added: 0000, 000D
  unhinted/NotoSansKhmerUI-Bold.ttf
    version: 1.02 vs 1.03 
    size: 38576 vs 38960 (384 bytes bigger)
    tables: changed post(+368), cmap(+16), 2 others
    chars: 190 vs 192 (2 more chars)
    cmap added: 0000, 000D
  unhinted/NotoSansKhmerUI-Regular.ttf
    version: 1.02 vs 1.03 
    size: 40292 vs 40676 (384 bytes bigger)
    tables: changed post(+368), cmap(+16), 2 others
    chars: 190 vs 192 (2 more chars)
    cmap added: 0000, 000D

### CODE REVIEW

**Comment by dougfelt** [comment]
@jungshik, please take a (close) look.  I almost undid some of your fixes to Khmer because my copy was not current, so had to rebase and fix.

**Comment by jungshik** [comment]
Sorry that I missed this somehow. 

> unhinted/NotoSansKhmerUI-Regular.ttf
> cmap removed: 0020
> cmap added: 0000, 000D

Why was space removed from this font?

**Comment by dougfelt** [comment]
Woah, I missed that too.  It should be there, I must have deleted it by accident.

**Comment by jungshik** [comment]
Yeah, gid=3 is there for U+0020. :-)

**Comment by dougfelt** [comment]
Updated the commit and comment (rewrote history).

**Comment by dougfelt** [comment]
@jungshik, please take another look, thanks

**Comment by jungshik** [comment]
Sorry for the delay.  I compared post and cmap tables of two versions (head and yours). 

LGTM

**Pull request merged**
