### PR TITLE
FAQ: Explain UI/non-UI versions

### PR DESCRIPTION
**Pull request by davelab6**
Closes https://github.com/googlei18n/noto-fonts/issues/531

### CODE REVIEW

**Comment by roozbehp** [comment]
They are not for Android UI only, but also for anywhere where there are limits on the vertical limits.

**Comment by dougfelt** [comment]
But the actual limits to which they conform do come from Android, no?

**Comment by roozbehp** [comment]
Yes, the numbers come from Android (from historic Roboto metrics, really), but the usage of the UI fonts is not limited to Android. My guess is ChromeOS also uses them. /cc @jungshik should have better insight.

**Comment by brawer** [comment]
Just curious, why is it a separate font? Couldn’t we ship just one font, and select glyph variants via an OpenType feature?

**Comment by dougfelt** [comment]
Overall font metrics are different.  We'd also need a custom feature and code to apply it in the required places.  Easier to just have the entire font be different.

**Comment by davelab6** [comment]
I agree with doug, although maybe we could move them in the repo to their
own directory with its own Readme?

**Comment by dougfelt** [comment]
BTW, some scripts work fine in UIs without having to be extensively tweaked to conform to the UI metrics.  The fonts with the 'UI' naming have some design compromises in order to conform, and have a preferred counterpart (the font without the UI name) for use in body text.  This probably also needs some explanation.

**Comment by davelab6** [comment]
I've updated the PR with the extra info in this discussion - thanks all!

**Comment by roozbehp** [comment]
LGTM.

**Comment by dougfelt** [comment]
Thanks.

**Pull request merged**
